config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'carts/show', to: 'carts#show', as: 'carts_show'
  post 'carts/add_cart', to: 'carts#add_cart'
  patch 'carts/change_quantity/:array_index', to: 'carts#change_quantity', as: 'carts_change_quantity'
  delete 'carts/:array_index', to: 'carts#destroy', as: 'carts'
  get '/purchase_completed', to: 'static_pages#purchase_completed', as: 'purchase_completed'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :orders
  resources :products
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  belongs_to :user_classification, optional: true
  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, :first_name, :zipcode, :municipality, :prefecture, :address, :apartments, :email, :phone_number, presence: true
  validates :last_name, :first_name, length: { maximum: 10 }
  validates :zipcode, format: { with: /\A[a-z0-9]+\z/i }, length: { is: 7 }, allow_blank: true
  validates :municipality, length: { maximum: 10 }
  validates :prefecture, length: { maximum: 5 }
  validates :address, :apartments, length: { maximum: 15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }, allow_blank: true
  validates :phone_number, format: { with: /\A[a-z0-9]+\z/i }, length: { maximum: 15 }, allow_blank: true
  validates :delete_flag, inclusion: { in: [true, false] }
  has_secure_password
  validates :password, presence: true, length: { in: 6..15 }, format: { with: /\A[a-z0-9]+\z/i }, allow_nil: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "新規作成に成功しました。"
      redirect_to @user
    else
      flash.now[:danger] = "正しい値を入力してください。"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "更新に成功しました。"
      redirect_to @user
    else
      flash.now[:danger] = "正しい値を入力してください。"
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy!
    redirect_to :root
  end

  private

    def user_params
      params.require(:user).permit(
        :last_name, :first_name, :zipcode, :prefecture, :municipality, :address,
        :apartments, :email, :phone_number, :company_name, :password, :password_confirmation
      )
    end
end

app/views/users/edit.html.erb
<% provide(:title, "ユーザ情報修正画面") %>


    <div class="container">
      <h3 class="text-center">ユーザー情報修正</h3>

      <%= form_for(@user, html: { class: "form-inline", id: "userinfo" }) do |f| %>

        <%#= render 'shared/error_messages' %>

        <div class="form-group col-12 mt-4">
          <%= f.label :name, "氏名", class: "col-3" %>
          <%= f.label :last_name, "姓", class: "col-1" %>
          <%= f.text_field :last_name, class: "col-3 p-0 lname" %>
          <%= f.label :first_name, "名", class: "col-1" %>
          <%= f.text_field :first_name, class: "col-3 p-0 fname" %>
        </div>

        <div class="form-group col-12 mt-4">
          <%= f.label :zipcode, "住所", class: "col-sm-3" %>
          <%= f.label :zipcode, "〒", class: "col-sm-1 text-right" %>
          <%= f.number_field :zipcode, class: "col-sm-3 p-0" %>
        </div>

        <div class="form-group col-12 mt-4">
          <%= f.label :prefecture, "都道府県", class: "col-sm-4 text-right" %>
        </div>

        <div class="form-group col-12 mt-4">
          <%= f.label :municipality, "市町村区", class: "col-sm-4 text-right" %>
          <%= f.text_field :municipality, class: "col-sm-7 p-0" %>
        </div>

        <div class="form-group col-12 mt-4">
          <%= f.label :address, "番地", class: "col-sm-4 text-right" %>
          <%= f.text_field :address, class: "col-sm-7 p-0" %>
        </div>

        <div class="form-group col-12 mt-4">
          <%= f.label :apartments, "マンション<br>部屋番号".html_safe, class: "col-sm-4 text-right" %>
          <%= f.text_field :apartments, class: "col-sm-7 p-0" %>
        </div>

        <div class="form-group col-12 mt-4">
          <%= f.label :email, "メールアドレス", class: "col-sm-4" %>
          <%= f.email_field :email, class: "col-sm-7 p-0" %>
        </div>

        <div class="form-group col-12 mt-4">
          <%= f.label :phone_number, "電話番号", class: "col-sm-4" %>
          <%= f.telephone_field :phone_number, class: "col-sm-7 p-0" %>
        </div>

        <div class="text-center mt-5">
          <%= f.submit "修正", class: "btn btn-primary pl-4 pr-4 fixbtn" %>
          <%= link_to "退会", user_path(current_user.id), method: :delete, data: { confirm: "ユーザーデータが全て削除されます。本当に退会しますか？" }, class: "btn btn-danger pl-4 pr-4" %>
        </div>

      <% end %>
    </div>

app/views/users/new.html.erb
<% provide(:title, "お客様情報登録") %>

<div class="container" id="new_user">
  <h3 class="text-center">お客様情報登録</h3>
  <%= form_with(model: @user, local: true, url: signup_path) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="form-group">
      <label>氏名</label>
      <div class="form-inline">
        <%= f.label "姓", class: "m-1" %>
        <%= f.text_field :last_name, class: "form-control lname" %>
        <%= f.label "名", class: "m-1" %>
        <%= f.text_field :first_name, class: "form-control lname" %>
      </div>
    </div>

    <div class="form-group mt-3">
      <%= f.label "郵便番号", class: "" %>
      <%= f.text_field :zipcode, class: "ml-4 col-5 form-control" %>
    </div>

    <div class="form-inline" id="address">
      <label>住所</label>
      <div class="form-group col-12">
        <%= f.label "都道府県", class: "col-sm-3" %>
        <div class="col-sm-9">
          <%= f.text_field :prefecture, class: "form-control" %>
        </div>
      </div>
      <div class="form-group col-12 mt-2">
        <%= f.label "市町村区", class: "col-sm-3" %>
        <div class="col-sm-9">
          <%= f.text_field :municipality, class: "form-control" %>
        </div>
      </div>
      <div class="form-group col-12 mt-2">
        <%= f.label "番地", class: "col-sm-3" %>
        <div class="col-sm-9">
          <%= f.text_field :address, class: "form-control" %>
        </div>
      </div>
      <div class="form-group col-12 mt-1">
        <%= f.label "マンション・部屋番号", class: "col-sm-6" %>
      </div>
      <div class="form-group col-12 mt-1">
        <div class="col-sm-3"></div>
        <div class="col-sm-9">
          <%= f.text_field :apartments, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group mt-2">
      <%= f.label "メールアドレス", class: "" %>
      <%= f.email_field :email, class: "ml-4 form-control mailform" %>
    </div>

    <div class="form-group mt-2">
      <%= f.label "電話番号", class: "" %>
      <%= f.telephone_field :phone_number, class: "ml-4 form-control telform" %>
    </div>

    <div class="form-group mt-2">
      <%= f.label "パスワード", class: "" %>
      <%= f.password_field :password, class: "ml-4 col-8 form-control" %>
    </div>

    <div class="form-group mt-2">
      <%= f.label "パスワード再入力", class: "" %>
      <%= f.password_field :password_confirmation, class: "ml-4 col-8 form-control" %>
    </div>

    <div class="text-center mt-4">
      <%= f.submit "登録", class: "btn btn-primary col-4 mb-4" %>
      <p><%= link_to "ログインはこちらから", login_path, class: "info" %></p>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, "ユーザ情報画面") %>

<div class="container">

  <div class="container text-center">
    <h1 class="title font-weight-bold mb-5">ユーザー情報</h1>
    <table class="table table-borderless">
      <tbody><tr>
        <td>ユーザーID</td>
        <td class="text-left"><%= @user.id %></td>
      </tr>
      <tr>
        <td>氏名</td>
        <td class="text-left"><%= "#{@user.last_name} #{@user.first_name}" %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td class="text-left">
          <p><%= "〒#{@user.zipcode.to_s.insert(3, "-")} "%></p>
          <p><%= "#{@user.prefecture}#{@user.municipality}#{@user.address}#{@user.apartments}" %></p>
        </td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td class="text-left"><%= @user.phone_number %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td class="text-left"><%= @user.email %></td>
      </tr>
    </tbody></table>
  </div>

  <div class="text-center my-5">
    <%= link_to "修正/退会する", edit_user_path, class: "btn btn-lg btn-primary" %>
  </div>

</div>