config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'carts/show', to: 'carts#show', as: 'carts_show'
  post 'carts/add_cart', to: 'carts#add_cart'
  patch 'carts/change_quantity/:array_index', to: 'carts#change_quantity', as: 'carts_change_quantity'
  delete 'carts/:array_index', to: 'carts#destroy', as: 'carts'
  get '/purchase_completed', to: 'static_pages#purchase_completed', as: 'purchase_completed'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :orders
  resources :products
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :logged_in_user

  def show
    return if session[:cart].blank?

    # view用：カート情報を配列に格納
    @cart = []
    session[:cart].each do |cart|
      product = Product.find(cart["product_id"])
      category_name = product.category.category_name
      subtotal = product.price * cart["quantity"].to_i
      @cart.push([product.product_name, category_name, product.price, cart["quantity"].to_i, subtotal])
    end
    # カート内の合計を計算
    @total_amount = total_amount(@cart)
  end

  def add_cart # rubocop:disable Metrics/AbcSize
    if session[:cart].blank?
      session[:cart] = [{ product_id: params[:product_id], quantity: params[:quantity].to_i }]
    else
      # カート内に既にある商品（数量追加）
      if index = session[:cart].pluck("product_id").index(params[:product_id]) # rubocop:disable Lint/AssignmentInCondition
        session[:cart][index]["quantity"] += params[:quantity].to_i
      else
        session[:cart].push({ product_id: params[:product_id], quantity: params[:quantity].to_i })
      end
    end
    redirect_to carts_show_path
  end

  def change_quantity
    session[:cart][params[:array_index].to_i]["quantity"] = params[:quantity]
    redirect_to carts_show_path
  end

  def destroy
    session[:cart].delete_at(params[:array_index].to_i)
    redirect_to carts_show_path
  end

  def total_amount(cart)
    cart.sum{_1[4]}
  end
end

app/views/carts/show.html.erb
<% provide(:title, "カート内一覧表示") %>

<div class="container">
  <div class="row">
    <div class="col">
      <div class="card lead p-3 mt-3">
        <p>お届け先</p>
        <div class="row">
          <p class="px-4"><%= current_user.zipcode %></p>
          <p class="pl-4">
            <%= current_user.prefecture %><%= current_user.municipality %><%= current_user.address %>
          </p>
        </div>
        <p class="pl-2 offset-sm-2"><%= current_user.last_name %><%= current_user.first_name %> 様</p> 
      </div>
    </div>
  </div>
  
  <% if @cart.nil? %>
    <h3 class="text-center">
      カートに商品はありません
    </h3>
  <% else %>
    <div class="my-5 table-responsive-md text-center size">
      <table class="table table-borderless text-nowrap">
        <thead>
          <tr class="thead table-border">
            <th scope="col">No</th>
            <th scope="col">商品名</th>
            <th scope="col">商品カテゴリ</th>
            <th scope="col">値段</th>
            <th scope="col">個数</th>
            <th scope="col">小計</th>
          </tr>
        </thead>
        <tbody class="table-border-responsive">
          <% if @cart.present? %>
            <% @cart.each.with_index(0) do |cart, i| %>
              <tr>
                <th scope="row"><%= i+1 %></th>
                <td data-label="商品名"><%= cart[0] %></td>
                <td data-label="商品カテゴリ"><%= cart[1] %></td>
                <td data-label="値段"><%= cart[2] %></td>
                <%= form_with(url: carts_change_quantity_path(i), method: :patch, local: true) do |f| %>
                  <td><%= f.number_field :quantity, value: cart[3], min: 1 %> 個</td>
                  <td data-label="小計"><%= cart[4] %>円</td>
                  <td><%= f.submit "変更", class: "btn btn-sm btn-primary" %></td>
                <% end %>
                <%= form_with(url: carts_path(i), method: :delete, local: true) do |f| %>
                  <td><%= f.submit "削除", class: "btn btn-sm btn-danger" %></td>
                <% end %>
              </tr>
            <% end %>
          <% end %>
          <tr class="table-border">
            <th></th>
            <td id="responsive-none"></td>
            <td id="responsive-none"></td>
            <td id="responsive-none"></td>
            <td class="total">合計</td>
            <td><%= @total_amount %>円</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="text-center mt-5">
      <%= link_to "買い物を続ける", products_path, class: "btn btn-success pl-2 pr-2 cart_button" %>
      <%= link_to "注文を確定する", orders_path, method: :post, class: "btn btn-primary pl-2 pr-2" %>
    </div>
  <% end %>
</div>