config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'carts/show', to: 'carts#show', as: 'carts_show'
  post 'carts/add_cart', to: 'carts#add_cart'
  patch 'carts/change_quantity/:array_index', to: 'carts#change_quantity', as: 'carts_change_quantity'
  delete 'carts/:array_index', to: 'carts#destroy', as: 'carts'
  get '/purchase_completed', to: 'static_pages#purchase_completed', as: 'purchase_completed'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :orders
  resources :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  belongs_to :sale_status, optional: true
  belongs_to :product_status, optional: true
  has_many :purchases, dependent: :destroy
  has_many :order_details, dependent: :nullify

  validates :product_name, :price, presence: true
  # 商品検索
  def self.search(search_product_name, category_id)
    products = self.where(category_id: category_id)
    products = self.where("product_name LIKE ?", "%#{search_product_name}%") if search_product_name.present?
    products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_user

  PER = 15
  def index
    # 商品登録しているカテゴリのみ取得
    @categories = Category.joins(:products).where.not("products.category_id" => nil).distinct
    return unless params[:search_button]

    @products = Product.includes(:category).search(params[:search_product_name], params[:category_id]).page(params[:page]).per(PER)
    flash.now[:notice] = "商品が見つかりません。" if @products.blank?
  end

  def show
    @product = Product.find_by(id: params[:id])
  end
end

app/views/products/index.html.erb
<% provide(:title, "商品検索画面") %>

<div class="container">
  <h3 class="text-center">商品検索画面</h3>
  <div class="d-flex justify-content-center">
    <%= form_with(url: products_path, method: :get, local: true, html: {class:"w-100"}) do |f| %>
      <div class="text-left mx-3">
        <%= f.label "商品カテゴリー", class: "m-1" %>
        <%= f.collection_select :category_id, @categories, :id, :category_name %><br>
        <div class="vertical-align-em">
          <%= f.label "商品名", class: "m-1" %>
          <%= f.text_field :search_product_name, class:"w-50" %>
          <%= f.submit '検索', name:"search_button", class:"btn btn-sm btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>

  <% if @products.present? %>
    <table class="product-index">
      <caption id="caption-side">
        <% if @products.total_count > @products.count %>
          <%= "表示: #{@products.count}件（全#{@products.total_count}件）" %>
        <% else %>
          <%= "全#{@products.total_count}件" %>
        <% end %>
      </caption>
      <thead>
        <tr class="bgcolor">
          <th>商品名</th>
          <th>商品カテゴリ</th>
          <th>価格</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td class="text-left"><%= product.product_name %></td>
            <td><%= product.category.category_name %></td>
            <td><%= product.price %></td>
            <td>
              <%= button_to "商品詳細", product_path(product), method: :get, class:"btn btn-sm btn-primary my-auto" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="pagination justify-content-center">
      <%= paginate @products %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<% provide(:title, "商品詳細画面") %>

<div class="container text-center">

  <% if @product.present? %>
    <h1 class="title font-weight-bold mb-5">商品情報</h1>
    <h4 class="title font-weight-bold mb-5"><%= "商品 #{ @product.id }" %>

      <p class="text-right"><%= "商品カテゴリ: #{@product.category[:category_name]}" %></p>

      <p class="text-left">商品説明</p>
      <p class="text-left"><%= @product.product_name %></p>
      <br>
      <p class="text-left"><%= "価格: #{@product.price.to_s(:delimited)} 円" %></p>

      <%= form_with(url: carts_add_cart_path, method: :post, local: true) do |f| %>
        <div class="d-flex justify-content-center">
          <%= f.label :quantity, "購入個数" %>
          <%= f.number_field :quantity, value: 1, min: 1 %>
          <p>個</p>
          <%= hidden_field_tag :product_id, @product.id %>
          <%= f.submit "カートへ", class: "btn btn-lg btn-primary" %>
        </div>
    </h4>
    <% end %>

  <% else %>
    <h2 class="col-12 title font-weight-bold mb-5"><%= "該当商品が見つかりませんでした…" %></h2>
    <h3 class="title font-weight-bold mb-5"><%= "商品検索画面に戻り、やり直して下さい" %></h3>

    <%= form_with do |f| %>
      <div class="d-flex justify-content-center">
        <%= link_to "商品検索画面へ", products_path, class: "btn btn-lg btn-primary" %>
      </div>
    <% end %>

  <% end %>
</div>