config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'carts/show', to: 'carts#show', as: 'carts_show'
  post 'carts/add_cart', to: 'carts#add_cart'
  patch 'carts/change_quantity/:array_index', to: 'carts#change_quantity', as: 'carts_change_quantity'
  delete 'carts/:array_index', to: 'carts#destroy', as: 'carts'
  get '/purchase_completed', to: 'static_pages#purchase_completed', as: 'purchase_completed'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :orders
  resources :products
end

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom py-3">
  <div class="container">
    <%= link_to '探求学園Rails専攻', root_path, class: "flogo" %>
    <div class="text-muted d-flex align-items-end copyright">&copy; 2020 QuestAcademia, All rights reserved</div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar fixed-top">
  <div class="container">
    <h2><%= link_to '探求学園Rails専攻', root_path, class:"hlogo font-weight-bold" %></h2>
    <% if logged_in? %>
      <%= link_to "#{current_user.last_name} #{current_user.first_name} さん", user_path(current_user), class:"ml-auto username" %>
    <% else %>
      <ul class="nav nav-right">
        <li class="mr-4"><%= link_to 'ログイン', login_path, class:"hmenu" %></li>
        <li><%= link_to '新規登録', signup_path, class:"hmenu" %></li>
      </ul>
    <% end %>
  </div>
  <% if logged_in? %>
    <div class="container">
      <div class="ml-auto navmenu">
        <div class="d-flex justify-content-around w-100">
          <%= link_to '商品検索', products_path, class:"hmenu" %>
          <%= link_to 'カート', carts_show_path, class:"hmenu" %>
          <%= link_to '注文履歴', '#', class:"hmenu" %>
          <%= link_to 'ユーザ情報', user_path(current_user), class:"hmenu" %>
          <%= link_to 'ログアウト', logout_path, method: :delete, class:"hmenu" %>
        </div>
      </div>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- header -->
    <%= render 'layouts/header' %>
    
    <main id="<%= "login-margin" if logged_in? %>">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
      
      <%= yield %>
    </main>
    
    <!-- header -->
    <%= render 'layouts/footer' %>
  </body>
</html>